name: Generate and Deploy Sitemap

on:
  workflow_dispatch:  # Abilita esecuzione manuale

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Installa le dipendenze (se necessarie)
      - name: Install dependencies
        run: python -m pip install --upgrade pip

      # Genera la sitemap
      - name: Generate Sitemap
        run: python scripts/generate_sitemap.py

      # Aggiorna il branch main con la nuova sitemap
      - name: Commit and Push Sitemap
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m 'Update sitemap.xml'
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
